#!/usr/bin/env bash
# Downloads the latin + latin-ext subsets of the site's typefaces from Google
# Fonts and writes src/styles/fonts.css pointing at /fonts/*.woff2.
# Self-hosting keeps the render-blocking font request same-origin.
#
# Run from the repo root:  bash scripts/fetch-fonts.sh
set -euo pipefail
cd "$(dirname "$0")/.."

UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"
API="https://fonts.googleapis.com/css2"
QUERY="family=Fraunces:opsz,wght,SOFT,WONK@9..144,300..900,0..100,0..1&family=IBM+Plex+Sans:wght@300..600&family=IBM+Plex+Mono:wght@400;500&display=swap"

mkdir -p public/fonts
curl -sSf -A "$UA" "$API?$QUERY" -o /tmp/gf-src.css

python3 - <<'PY'
import re, pathlib, subprocess

css = pathlib.Path('/tmp/gf-src.css').read_text()
blocks = re.findall(r'/\*\s*([a-z0-9\-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})', css)
KEEP = {'latin', 'latin-ext'}

out, jobs = [], []
for subset, block in blocks:
    if subset not in KEEP:
        continue
    fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
    wght = re.search(r'font-weight:\s*([^;]+);', block).group(1).strip()
    url = re.search(r'url\((https://fonts\.gstatic\.com[^)]+)\)', block).group(1)
    name = f"{fam.lower().replace(' ', '-')}-{wght.replace(' ', '-')}-{subset}.woff2"
    jobs.append((name, url))
    out.append(block.replace(url, f"/fonts/{name}"))

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")
for name, url in jobs:
    subprocess.run(['curl', '-sSf', '-A', UA, '-o', f'public/fonts/{name}', url], check=True)

pathlib.Path('src/styles/fonts.css').write_text(
    "/* Generated by scripts/fetch-fonts.sh — do not edit by hand.\n"
    "   Latin + latin-ext subsets, self-hosted so the render-blocking font\n"
    "   request stays same-origin and no third party sees visitor traffic. */\n\n"
    + '\n\n'.join(out) + '\n'
)
print(f"wrote {len(jobs)} files and {len(out)} @font-face blocks")
PY
